coworking/urls.py
from django.urls import path

from . import views
app_name = 'coworkings'

urlpatterns = [
    path('', views.home, name="home"),
    path('coworking/category/<int:category_id>/', views.category,
         name="category"),
    path('coworking/<int:id>/', views.coworking, name="coworking"),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('coworking.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projeto/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('coworking.urls')),

]

coworking/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name


class Country(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name


class State(models.Model):
    name = models.CharField(max_length=65)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Municipality(models.Model):
    name = models.CharField(max_length=65)
    state = models.ForeignKey(State, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    

class Neighborhood(models.Model):
    name = models.CharField(max_length=65)
    municipality = models.ForeignKey(Municipality, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Coworking(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    description_is_html = models.BooleanField(default=False)
    property_size = models.IntegerField()
    equipment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='coworkings/covers/%Y/%m/%d/',
                              blank=True, default='')
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True,
        default=None,
    )
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True
    )

    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    state = models.ForeignKey(State, on_delete=models.SET_NULL, null=True)
    municipality = models.ForeignKey(Municipality, on_delete=models.SET_NULL, null=True)
    neighborhood = models.ForeignKey(Neighborhood, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

coworking/views.py
from django.shortcuts import get_list_or_404, get_object_or_404, render

from coworking.models import Coworking


def home(request):
    coworkings = Coworking.objects.filter(
        is_published=True,
    ).order_by('id')

    return render(request, 'coworking/pages/home.html', context={
        'coworkings': coworkings})


def category(request, category_id):
    coworkings = get_list_or_404(
        Coworking.objects.filter(
            category__id=category_id,
            is_published=True,
        ).order_by('-id')
    )

    return render(request, 'coworking/pages/category.html', context={
        'coworkings': coworkings,
        'title': f'{coworkings[0].category.name} - Category | '
    })


def coworking(request, id):
    coworking = get_object_or_404(Coworking, pk=id, is_published=True,)
    return render(request, 'coworking/pages/coworking-view.html', context={
        'coworking': coworking,
        'is_detail_page': True,
    })

coworking/templates/coworking/contato.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Contato</h1>
</body>
</html>

coworking/templates/coworking/home.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Coworking</title>
</head>
<body>
    <h1>Coworking 1</h1>
</body>
</html>

coworking/templates/coworking/pages/category.html
{% extends 'global/base.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
<div class="main-content main-content-list container">
    {% for coworking in coworkings %}
        {% include 'coworking/partials/coworking.html' %}
    {% endfor %}
</div>
{% endblock content %}

coworking/templates/coworking/pages/coworking-view.html
{% extends 'global/base.html' %}

{% block title %}{{ coworking.title }} | {% endblock title %}

{% block content %}
<div class="main-content main-content-detail container"  >
    {% include 'coworking/partials/coworking.html' %}
</div>
{% endblock content %}

coworking/templates/coworking/pages/home.html
{% extends 'global/base.html' %}

{% block title %}Home | {% endblock title %}

{% block content %}
<div class="main-content main-content-list container">
    {% for coworking in coworkings %}
        {% include 'coworking/partials/coworking.html' %}
    {% endfor %}
</div>
{% endblock content %}

coworking/templates/coworking/partials/coworking.html
<div class="coworking coworking-list-item">
    <a class="coworking-read-more button button-dark button-full-width" href="/coworking/3/">
        {% if coworking.cover %}
            <div class="coworking-cover">
                <a href="{% url 'coworkings:coworking' coworking.id %}">
                    <img src="{{ coworking.cover.url }}" alt="Temporário">
                </a>
            </div>
        {% endif %}
        {% if coworking.author is not None %}
            <span class="coworking-author-item">
                <i class="fas fa-user"></i>
                {% if coworking.author.first_name %}
                    {{ coworking.author.first_name }} {{ coworking.author.last_name }}
                {% else %}
                    {{ coworking.author.username }}
                {% endif %}
            </span>
        {% endif %}
        <div class="coworking-location">
            <a>
                <h2>{{coworking.cities}}, {{coworking.country}}</h2>
            </a>
        </div>
        {% if coworking.category is not None %}
            <span class="coworking-author-item">
                <a href="{% url 'coworkings:category' coworking.category.id %}">
                    <i class="fas fa-layer-group"></i>
                    <span>{{ coworking.category.name }}</span>
                </a>
            </span>
        {% else %}
            <span>Categoria não disponível</span>
        {% endif %}
        <div class="coworking-author-item">
            <i class="fas fa-calendar-alt"></i>
            <span>{{ coworking.created_at|date:"d/m/Y" }} às {{ coworking.created_at|date:"H:i" }} -
                  {{ coworking.created_at|date:"d/m/Y" }} às {{ coworking.created_at|date:"H:i" }}
            </span>
        </div>
        <div class="coworking-meta coworking-preparation">
            <div>R$ 15/h</div>
        </div>
        
        {% comment %} <footer class="coworking-footer">
            <a class="coworking-read-more button button-dark button-full-width" href="/coworking/3/">
                <i class="fas fa-eye"></i>
                <span>ver mais...</span>
            </a>
        </footer> {% endcomment %}

        {% if is_detail_page is True %}
            <div class="preparation-steps">
                {{ coworking.description|linebreaksbr }}
                {% if coworking.description_is_html is True %}
                    {{ coworking.description|safe }}
                {% else %}
                    {{ coworking.description|linebreaksbr }}
                {% endif %}
            </div>
        {% endif %}
    </a>
</div>

coworking/templates/coworking/partials/footer.html
<footer class="main-footer">
    <div class="developer">
      <a href="https://www.otaviomiranda.com.br/" target="_blank" rel="noreferrer noopener">By Space To work</a>
    </div>
  
    <div class="powered">
      <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
    </div>
</footer>

coworking/templates/coworking/partials/head.html
{% load static %}

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/fontawesome.min.css"
    integrity="sha512-P9vJUXK+LyvAzj8otTOKzdfF1F3UYVl13+F8Fof8/2QNb8Twd6Vb+VD52I7+87tex9UXxnzPgWA3rH96RExA7A=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/brands.min.css"
    integrity="sha512-sVSECYdnRMezwuq5uAjKQJEcu2wybeAPjU4VJQ9pCRcCY4pIpIw4YMHIOQ0CypfwHRvdSPbH++dA3O4Hihm/LQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/solid.min.css"
    integrity="sha512-tk4nGrLxft4l30r9ETuejLU0a3d7LwMzj0eXjzc16JQj+5U1IeVoCuGLObRDc3+eQMUcEQY1RIDPGvuA7SNQ2w=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="{% static 'coworking/css/styles.css' %}"/>
<link rel="stylesheet" href="{% static 'global/css/global-style.css' %}"/>

coworking/templates/coworking/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class="main-logo" href="{% url 'coworkings:home' %}">
                <span class="main-logo-text">Coworking</span>
            </a>
        </h1>
    </div>
</header>

coworking/templates/coworking/partials/search.html
<div class="search-container">
    <div class="container">
        <form action="" class="search-form">
            <input type="search" class="search-input" name="search">
            <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
        </form>
    </div>
</div>